### PR TITLE
Add repo-wide linting

### PR DESCRIPTION
**Pull request by ethitter**
### Make sure you complete these items:

- [ ] Updated root CHANGELOG.md with summary of changes under `Unpublished` section
- [ ] `npm run prod` in this repo outputs expected changes (excepting the issue with re-ordered partials in larva-css algorithms partials - see [LRVA-1885](https://jira.pmcdev.io/browse/LRVA-1885))
- [ ] If adding a new pattern, in the PR comment, included a screenshot and link to the static Vercel deployment
- [ ] If changes to build scripts or the Node.js server, tested changes in pmc-spark [via a pre-release](https://confluence.pmcdev.io/x/XhOeAw)
- - If changes to build tools: npm scripts `prod`, `lint`, and `dev` scripts run as expected
- - If changes to Larva server: Static site generates as expected in a theme  (avail. on a URL {brand}.stg.larva.pmcdev.io)

### CODE REVIEW

**Comment by pattiereaves** [comment]
Update on where we left off:
- if you don't install `@wordpress/eslint-plugin@latest` at the root package.json, running lint-fix:js will give the error that "ESLint couldn't find the plugin "@wordpress/eslint-plugin"."
- if you do install it, it will give the following error 
>Error: .eslintrc » @penskemediacorp/eslint-config » plugin:@wordpress/recommended » /Users/preaves/Development/work/pmc-larva/node_modules/@wordpress/eslint-plugin/configs/recommended-with-formatting.js » /Users/preaves/Development/work/pmc-larva/node_modules/@wordpress/eslint-plugin/configs/esnext.js » /Users/preaves/Development/work/pmc-larva/node_modules/@wordpress/eslint-plugin/configs/es5.js » /Users/preaves/Development/work/pmc-larva/node_modules/@wordpress/eslint-plugin/configs/jsdoc.js:
        Configuration for rule "jsdoc/check-line-alignment" is invalid:
        Value ["always",{"tags":["param","arg","argument","property","prop"],"preserveMainDescriptionPostDelimiter":true}] should NOT have more than 1 items.

    at ConfigValidator.validateRuleOptions (/Users/preaves/Development/work/pmc-larva/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:142:23)
    at /Users/preaves/Development/work/pmc-larva/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:197:18
    at Array.forEach (<anonymous>)
    at ConfigValidator.validateRules (/Users/preaves/Development/work/pmc-larva/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:194:34)
    at ConfigValidator.validateConfigArray (/Users/preaves/Development/work/pmc-larva/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:320:18)
    at CascadingConfigArrayFactory._finalizeConfigArray (/Users/preaves/Development/work/pmc-larva/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:493:23)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/Users/preaves/Development/work/pmc-larva/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:299:21)
    at FileEnumerator._iterateFilesRecursive (/Users/preaves/Development/work/pmc-larva/node_modules/eslint/lib/cli-engine/file-enumerator.js:445:49)
    at _iterateFilesRecursive.next (<anonymous>)
    at FileEnumerator.iterateFiles (/Users/preaves/Development/work/pmc-larva/node_modules/eslint/lib/cli-engine/file-enumerator.js:296:49)

**Comment by jameswburke** [comment]
Updates
* Rebased with master, resolved conflicts, pushed new build.
* Fixed issue with `jsdoc/check-line-alignment` value.

When running linting, we get a conflict between eslint configuration files in our Larva root and in `packages/larva/scripts/config/.eslintrc.json`.

Do we need to adjust the command we run to avoid this conflict?

**Comment by pattiereaves** [comment]
## Where we left today:
- linting runs locally for most of us (Dan, Pattie, James) but number of errors may not match?
- there are a lot of errors that aren't fixed
- the task isn't throwing up an exit code in the action so even when the linting fails it doesn't fail the task 

## This can be merged when the following conditions are met:
- We should pull any linting file changes out of this PR so it is smaller
- We should get the task to throw up an error code so it fails the action

## Left to do:
- Eslint is not working in the pipeline, period 
  - Maybe related to eslint-config package needing to be published in order to 
  - Maybe need to merge the piece of this that bumps the dependency

**Review by pattiereaves — DISMISSED** [review]

**Review by pattiereaves — APPROVED** [review]
Stuff that is prettier related looks clean

**Review by jameswburke — APPROVED** [review]
:bee:

**Pull request merged**
