### PR TITLE
Pullquote module

### PR DESCRIPTION
**Pull request by saniyat**
### Doneness Checklist:

Pre-release # (or n/a):

- [ ] Updated root CHANGELOG.md with summary of changes under `Unpublished` section
- [ ] Ran the visual regression tests manually (see [the README](https://github.com/penske-media-corp/pmc-larva#running-visual-regression-tests) for details)
- [ ] `npm run prod` in this repo outputs expected changes (excepting the issue with re-ordered partials in larva-css algorithms partials - see [LRVA-1885](https://jira.pmcdev.io/browse/LRVA-1885))
- [ ] If changes to build scripts or the Node.js server, tested changes in pmc-spark [via a pre-release](https://confluence.pmcdev.io/x/XhOeAw)
- - If changes to build tools: npm scripts `prod`, `lint`, and `dev` scripts run as expected
- - If changes to Larva server: Static site generates as expected in a theme  (avail. on a URL {brand}.stg.larva.pmcdev.io)

### CODE REVIEW

**Comment by saniyat** [comment]
@laras126 Thanks. I have tried with the generation of the screenshot. All screenshots are passed in my local but in server getting 11 errors among 15. So, I revert my commit.

**Comment by pattiereaves** [comment]
@saniyat it looks like it's failing because "pullquote" was added to the list of components, and those lists are diffing in four screenshots. 

image

image

**Comment by saniyat** [comment]
@pattiereaves, Yap, new module "Pullquote" added. So, I have run the commands according to the readme file. My local successfully tested the changes and showed 15 files were passed. But when I push the screenshot, the PR shows 11 screenshots are not matching. So, I revert the commit (more errors generated by the commit).

Here is the link of the commit https://github.com/penske-media-corp/pmc-larva/pull/451/commits/901630a7cc6455c44e62f3c3303f4d43b9eb4a6e

I think it is an environment-related problem of the backstop.

**Comment by saniyat** [comment]
I think I figured out the problem. Let me check.

**Comment by pattiereaves** [comment]
I am getting the same 4 files failing in 901630a7cc6455c44e62f3c3303f4d43b9eb4a6e, though it looks like the diffs have to do with more of the sidebar being different:

image

**Review by laras126 — APPROVED** [review]
Wonderful, thank you Saniyat!

**Pull request merged**
