### PR TITLE
Move RS header css and js to RS theme

### PR DESCRIPTION
**Pull request by anischarolia-multidots**
### Make sure you complete these items:

- [X] Updated root CHANGELOG.md with summary of changes under `Unpublished` section
- [X] `npm run prod` in this repo outputs expected changes (excepting the issue with re-ordered partials in larva-css algorithms partials - see [LRVA-1885](https://jira.pmcdev.io/browse/LRVA-1885))
- [ ] If adding a new pattern, in the PR comment, included a screenshot and link to the static Vercel deployment
- [ ] If changes to build scripts or the Node.js server, tested changes in pmc-spark [via a pre-release](https://confluence.pmcdev.io/x/XhOeAw)
- - If changes to build tools: npm scripts `prod`, `lint`, and `dev` scripts run as expected
- - If changes to Larva server: Static site generates as expected in a theme  (avail. on a URL {brand}.stg.larva.pmcdev.io)

### CODE REVIEW

**Comment by rsalvucci** [comment]
It looks like there is a double header in the Visual Regression testing reference shots you uploaded. Is that correct?

**Comment by anischarolia-multidots** [comment]
> 

Yes, there are both normal and sticky headers in Visual Regression testing reference shots, because we have now removed the header CSS which was responsible for showing/hiding one header at a time.

**Comment by rsalvucci** [comment]
Does this need to be coordinated with @kjbenk before it gets approved, merged and released?

**Comment by kjbenk** [comment]
Thanks for pinging me here, but I believe this change will be fine for the SJ site. However, I agree the new screenshots look a bit off to me. Maybe the mocks should only include the normal header and not the sticky header?

**Comment by rsalvucci** [comment]
@anischarolia-multidots I talked with Pattie and Erick and the CSS to hide the sticky header should stay in Larva.

**Comment by anischarolia-multidots** [comment]
@rsalvucci I have added minimal CSS for the sticky header, the visual regression screenshots look good now.

**Review by rsalvucci — APPROVED** [review]

**Pull request merged**
